name: Build Docker images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      shell: bash
      run: |
        docker build . \
          --file Dockerfile \
          --tag python-latex:${{ matrix.python-version }}-$(date +%s) \
          --build-arg PYTHON_VERSION=${{ matrix.python-version }}
