name: Publish Docker images

on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@40891eba8c2bcd1309b07ba8b11232f313e86779
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y-%m-%dT%H:%M:%SZ')"
      
      - name: Get git commit SHA
        id: git_sha
        run: echo "::set-output name=git_sha::$(git rev-parse HEAD)"

      - name: Build and push Docker image
        uses: docker/build-push-action@4976231911ebf5f32aad765192d35f942aa48cb8
        with:
          context: .
          push: true
          tags: engineervix/python-latex:${{ matrix.python-version }}
          labels: |
            "org.opencontainers.image.title": "python-latex",
            "org.opencontainers.image.description": "Python ${{ matrix.python-version }}-slim-bullseye plus texlive and pandoc",
            "org.opencontainers.image.url": "https://github.com/engineervix/docker-python-latex",
            "org.opencontainers.image.source": "https://github.com/engineervix/docker-python-latex",
            "org.opencontainers.image.version": "${{ matrix.python-version }}",
            "org.opencontainers.image.licenses": "MIT"
            "org.opencontainers.image.created": "${{ steps.timestamp.outputs.timestamp }}",
            "org.opencontainers.image.revision": "${{ steps.git_sha.outputs.git_sha }}"
          build-args: PYTHON_VERSION=${{ matrix.python-version }}
